SELECT * FROM CUSTOMERS
--1
SELECT C.COMPANYNAME, C.CONTACTNAME FROM CUSTOMERS C
--2
SELECT * FROM CUSTOMERS C WHERE C.COUNTRY IN('USA','UK','GERMANY','FRANCE')
--3
SELECT * FROM CUSTOMERS C WHERE C.COMPANYNAME LIKE 'G%'
--4
SELECT * FROM CUSTOMERS C WHERE C.CITY = 'PARIS'
--5
SELECT * FROM CUSTOMERS C WHERE C.POSTALCODE LIKE '4%'
--6
SELECT * FROM CUSTOMERS C WHERE C.COUNTRY NOT IN ('CANADA','BRAZIL')
--7
SELECT DISTINCT(C.COUNTRY), COUNT(C.CUSTOMERID) AS NUMCUSTOMER FROM CUSTOMERS C GROUP BY C.COUNTRY
--8
SELECT * FROM CUSTOMERS C ORDER BY C.COUNTRY, C.CITY 
--9
SELECT C.CONTACTNAME,C.CONTACTTITLE FROM CUSTOMERS C WHERE C.CONTACTTITLE LIKE '%MANAGER'
--10
SELECT * FROM CUSTOMERS C WHERE C.COMPANYNAME LIKE '%''%' 
------------------------------
SELECT * FROM PRODUCTS 
--11
SELECT * FROM PRODUCTS P WHERE P.CATEGORYID = 4 AND P.UNITSINSTOCK > 50
--12
SELECT P.PRODUCTNAME, P.UNITPRICE, P.UNITSINSTOCK , P.UNITPRICE * P.UNITSINSTOCK AS NETSTOCK FROM PRODUCTS P 
--13
SELECT MAX(P.UNITPRICE) AS [MAX UNITPRICE], MIN(P.UNITPRICE) AS [MIN UNIT PRICE] FROM PRODUCTS P
--14
SELECT COUNT(P.PRODUCTID) AS PRODUCTCOUNT FROM PRODUCTS P WHERE P.UNITPRICE > 50
--15
SELECT P.CATEGORYID,COUNT(P.PRODUCTID) AS [CATEGORY COUNT] FROM PRODUCTS P GROUP BY P.CATEGORYID HAVING COUNT(P.PRODUCTID) > 10
--16
SELECT * FROM PRODUCTS P WHERE P.UNITSINSTOCK < P.REORDERLEVEL
--17
SELECT P.CATEGORYID, P.SUPPLIERID, COUNT(P.PRODUCTID) AS COUNT FROM PRODUCTS P GROUP BY P.CATEGORYID, P.SUPPLIERID ORDER BY P.CATEGORYID,P.SUPPLIERID
--18
SELECT P.PRODUCTID, P.PRODUCTNAME,P.UNITSINSTOCK, CASE
WHEN P.UNITSINSTOCK < 5 THEN 50
ELSE 30
END AS ORDEREDUNITS
FROM PRODUCTS P
--19
SELECT TOP 3 * FROM PRODUCTS P ORDER BY P.UNITPRICE DESC
--20
SELECT * FROM PRODUCTS P
WHERE (P.CATEGORYID = 1 AND (P.SUPPLIERID = 10 OR P.SUPPLIERID = 12)) OR (P.CATEGORYID = 4 AND (P.SUPPLIERID = 14 OR P.SUPPLIERID = 15))
----------------------------------
SELECT * FROM ORDERS
--21
SELECT * FROM ORDERS O WHERE DATEPART(MM,O.ORDERDATE) = 2
--22
SELECT COUNT(O.ORDERID) AS ORDERNUM, DATEPART(YYYY,O.ORDERDATE) AS YEAR FROM ORDERS O GROUP BY DATEPART(YYYY,O.ORDERDATE)
--23
SELECT O.SHIPCOUNTRY, COUNT(O.ORDERID) AS ORDERCOUNT FROM ORDERS O GROUP BY O.SHIPCOUNTRY
--24
SELECT * FROM ORDERS O ORDER BY DATEPART(MM,O.ORDERDATE)
--25
SELECT DISTINCT(O.SHIPCOUNTRY) FROM ORDERS O ORDER BY O.SHIPCOUNTRY
--26
SELECT O.CUSTOMERID, O.SHIPCITY, O.SHIPCOUNTRY, ISNULL(O.SHIPREGION,'NO REGION') AS SHIPREGION FROM ORDERS O
--27
SELECT TOP 1 * FROM ORDERS O ORDER BY O.ORDERDATE
--28
SELECT O.CUSTOMERID, DATEPART(YYYY,O.ORDERDATE), COUNT(O.ORDERID) FROM ORDERS O GROUP BY O.CUSTOMERID, DATEPART(YYYY,O.ORDERDATE) ORDER BY O.CUSTOMERID
--29
SELECT * FROM ORDERS O WHERE O.EMPLOYEEID = 4 AND DATEPART(MM,O.ORDERDATE) = 12
--30
SELECT O.EMPLOYEEID, DATEPART(YYYY,O.ORDERDATE) AS YEAR, DATEPART(MM,O.ORDERDATE) AS MONTH, COUNT(O.ORDERID) AS ORDERCOUNT FROM ORDERS O 
GROUP BY O.EMPLOYEEID, DATEPART(YYYY,O.ORDERDATE), DATEPART(MM,O.ORDERDATE)
----------------------------------
--31
SELECT * FROM [ORDER DETAILS] OD
--32
SELECT OD.PRODUCTID,OD.UNITPRICE,OD.QUANTITY, OD.UNITPRICE * QUANTITY AS TOTAL FROM [ORDER DETAILS] OD ORDER BY OD.UNITPRICE * QUANTITY DESC
--33
SELECT OD.PRODUCTID,OD.UNITPRICE,OD.QUANTITY, OD.UNITPRICE * OD.QUANTITY AS TOTAL,CASE
WHEN OD.UNITPRICE * OD.QUANTITY > 10000 THEN OD.UNITPRICE * OD.QUANTITY * 0.1
WHEN OD.UNITPRICE * OD.QUANTITY > 5000 THEN OD.UNITPRICE * OD.QUANTITY * 0.05
WHEN OD.UNITPRICE * OD.QUANTITY > 3000 THEN OD.UNITPRICE * OD.QUANTITY * 0.02
WHEN OD.UNITPRICE * OD.QUANTITY > 1000 THEN 300
ELSE 0
END AS DISCOUNT
FROM [ORDER DETAILS] OD ORDER BY OD.UNITPRICE * OD.QUANTITY DESC
--34
SELECT OD.ORDERID,SUM(OD.QUANTITY) AS [TOTAL ORDER] FROM [ORDER DETAILS] OD GROUP BY  OD.ORDERID
--35
SELECT MIN(OD.UNITPRICE*OD.QUANTITY) AS MIN, MAX(OD.UNITPRICE*OD.QUANTITY) AS MAX FROM [ORDER DETAILS] OD

