--JOIN AND SUBQUERY ASSIGNMENT

--1  LIST ALL THE PRODUCTS DETAILS WHOSE CATEGORY IS SAME AS 'TOFU'
SELECT * FROM PRODUCTS PO WHERE PO.CATEGORYID IN (SELECT P.CATEGORYID FROM PRODUCTS P WHERE P.PRODUCTNAME = 'TOFU')

--2  LIST ALL THE PRODUCTS DETAILS FOR THE CATEGORY 'BEVERAGES'
SELECT * FROM PRODUCTS P WHERE P.CATEGORYID IN (SELECT C.CATEGORYID FROM CATEGORIES C WHERE C.CATEGORYNAME = 'BEVERAGES')

--3  LIST ALL THE ORDERS PLACED BY THE COMPANY NAME "ISLAND TRADING"
SELECT * FROM ORDERS O WHERE O.CUSTOMERID IN (SELECT C.CUSTOMERID FROM CUSTOMERS C WHERE C.COMPANYNAME = 'ISLAND TRADING')

--4  LIST COMPANY NAME AND NO OF ORDER COUNT PLACED BY EACH COMPANY
SELECT COUNT(O.ORDERID) AS ORDERCOUNT, C.COMPANYNAME 
FROM CUSTOMERS C LEFT JOIN ORDERS O ON C.CUSTOMERID = O.CUSTOMERID GROUP BY C.COMPANYNAME 

--5  LIST ORDERID, CUSTOMER_COMAPNAYNAME FOR ALL THE ORDERS WHICH ARE HANDLE BY THE EMPLOYEES WHOSE TITLE IS "SALES MANAGER"
SELECT O.ORDERID,C.COMPANYNAME FROM ORDERS O LEFT JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
WHERE O.EMPLOYEEID IN (SELECT E.EMPLOYEEID FROM EMPLOYEES E WHERE E.TITLE = 'SALES MANAGER')

--6  LIST 3RD HIGHEST COSTLIEST PRODUCT
SELECT * FROM (SELECT DENSE_RANK() OVER (ORDER BY UNITPRICE DESC) RNK ,* FROM PRODUCTS P) AS E
WHERE E.RNK = 3

--7  FOR THE PRODUCT TABLE DISPLAY PRODUCTNAME AND CATEGORYNAME. ARRANGE AS PER THE CATEGORYNAME
SELECT P.PRODUCTNAME, C.CATEGORYNAME FROM PRODUCTS P LEFT JOIN CATEGORIES C ON P.CATEGORYID = C.CATEGORYID
ORDER BY C.CATEGORYNAME

--8  FOR THE ORDERS TABLE DISPLAY ORDERID CUSTOMER_COMPANYNAME AND EMPLOYEE_FULLNAME
SELECT O.ORDERID, C.COMPANYNAME, (E.FIRSTNAME+' '+E.LASTNAME) AS EMPLOYEE_FULLNAME
FROM ORDERS O JOIN EMPLOYEES E ON O.EMPLOYEEID = E.EMPLOYEEID JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID

--9  LIST ORDERID, EMPLOYEE_FULLNAME, CUSTOMER_COMPANYNAME, CATEGORYNAME, SUPPLIER_COMPANYNAME, PRODUCTNAME, ORDERDETAIS_UNIRPRICE, ORDERDETAILS_QUANTITY , NETSTOCK
SELECT O.ORDERID, (E.FIRSTNAME+' '+E.LASTNAME) AS EMPLOYEE_FULLNAME, C.COMPANYNAME, CA.CATEGORYNAME, SP.COMPANYNAME,
P.PRODUCTNAME, P.UNITPRICE, OD.QUANTITY, (P.UNITPRICE*P.UNITSINSTOCK) NETSTOCK 
FROM ORDERS O JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
JOIN EMPLOYEES E ON O.EMPLOYEEID = E.EMPLOYEEID 
JOIN [ORDER DETAILS] OD ON O.ORDERID = OD.ORDERID
JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
JOIN CATEGORIES CA ON P.CATEGORYID = CA.CATEGORYID
JOIN SUPPLIERS SP ON P.SUPPLIERID = SP.SUPPLIERID

--10  LIST ALL THE ORDERS (ORDERID, PRODUCTNAME) PLACED BY THE CUSTOMER IN LONDON
SELECT O.ORDERID, P.PRODUCTNAME FROM ORDERS O JOIN [ORDER DETAILS] OD ON O.ORDERID = OD.ORDERID
JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
WHERE O.CUSTOMERID IN(SELECT C.CUSTOMERID FROM CUSTOMERS C WHERE C.CITY = 'LONDON')

--11  FOR THE COSTLIEST PRODUCT DISPLAY PRODUCTNAME, UNITPRICE, CATEGORYNAME, SUPPLIER_CONTACTNAME
SELECT P.PRODUCTNAME, P.UNITPRICE, CA.CATEGORYNAME, SP.CONTACTNAME FROM (SELECT DENSE_RANK() OVER (ORDER BY UNITPRICE DESC) RNK,* FROM PRODUCTS) AS P
JOIN SUPPLIERS SP ON P.SUPPLIERID = SP.SUPPLIERID
JOIN CATEGORIES CA ON P.CATEGORYID = CA.CATEGORYID
WHERE RNK = 1

--12  LIST ALL THE PRODUCTNAME WHOSE ORDER PLACED IN MONTH OF AUGUST
SELECT P.PRODUCTNAME FROM ORDERS O JOIN [ORDER DETAILS] OD ON O.ORDERID = OD.ORDERID
JOIN PRODUCTS P ON OD.PRODUCTID=P.PRODUCTID
WHERE DATEPART(MM,O.OrderDate) = 8

--13  LIST ORDERID, QUANTITY FOR ALL THE ORDERS. ASSIGNED RANK AS PER THE HIGHEST OT LOWEST QUANTITY. DO NOT MISS ANY NUMBER WHILE ASSIGNING THE RANK
SELECT DENSE_RANK() OVER (ORDER BY OD.QUANTITY DESC) AS RNK, O.ORDERID, OD.QUANTITY
FROM ORDERS O JOIN [ORDER DETAILS] OD ON O.ORDERID = OD.ORDERID

--14 LIST ALL THE PRODUCTS FOR THE CATEGORY “DAIRY PRODUCT”
SELECT * FROM PRODUCTS P WHERE P.CATEGORYID IN (SELECT C.CATEGORYID FROM CATEGORIES C WHERE C.CATEGORYNAME = 'DAIRY PRODUCTS')

--15 LIST ALL THE PRODUCTS WHICH IS SUPPLIED BY THE COMPANY “BIGFOOT BREWERIES”  FOR THE CATEGORY “BEVERAGES”
SELECT * FROM PRODUCTS P WHERE 
P.SUPPLIERID IN (SELECT S.SUPPLIERID FROM SUPPLIERS S WHERE S.COMPANYNAME = 'BIGFOOT BREWERIES')
AND P.CATEGORYID IN (SELECT C.CATEGORYID FROM CATEGORIES C WHERE C.CATEGORYNAME = 'BEVERAGES')

--16 PRINT   CATEGORYNAME , SUPPLIER COMAPNY NAME  AND PRODUCT COUNT FOR EACH CATEGORY AND SUPPLIER
SELECT C.CATEGORYNAME, S.COMPANYNAME, COUNT(P.PRODUCTID) AS [PRODUCT COUNT]
FROM PRODUCTS P JOIN CATEGORIES C ON P.CATEGORYID = C.CATEGORYID
JOIN SUPPLIERS S ON P.SUPPLIERID = S.SUPPLIERID
GROUP BY C.CATEGORYNAME, S.COMPANYNAME

--17 PRINT REGION AND TERRITORYDESCRIPTION NAME IN ASCENDING ORDER
SELECT R.REGIONDESCRIPTION, T.TERRITORYDESCRIPTION FROM TERRITORIES T JOIN REGION R ON R.REGIONID = T.REGIONID
ORDER BY R.REGIONDESCRIPTION, T.TERRITORYDESCRIPTION

--18 PRINT  EMPLOYEES NAME, REGION NAME, CITY AND COUNTRY  --(CHECK FOR THE ERROR,  NO REGION RELATIONSHIP)
SELECT E.FIRSTNAME, ISNULL(R.REGIONDESCRIPTION,'NO REGION') AS REGION, E.CITY, E.COUNTRY FROM EMPLOYEES E
LEFT JOIN EMPLOYEETERRITORIES ET ON E.EMPLOYEEID = ET.EMPLOYEEID JOIN TERRITORIES T ON ET.TERRITORYID = T.TERRITORYID
LEFT JOIN REGION R ON T.REGIONID = T.REGIONID

--19 FOR EACH CATEGORIES PRINT CATEGORYNAME AND SUPPLIERS NAME
SELECT C.CATEGORYNAME, S.COMPANYNAME FROM CATEGORIES C JOIN PRODUCTS P ON P.CATEGORYID = C.CATEGORYID
JOIN SUPPLIERS S ON P.SUPPLIERID = S.SUPPLIERID
GROUP BY C.CATEGORYNAME, S.COMPANYNAME

--20 PRINT EMPLOYEE TITLEOFCOURTESY, EMPLOYEE FIRST + LASTNAME , EMPLOYEE TITLE, MANAGER TITLEOFCURTASY, MANAGER FIRSTNAME + LASTNAME, MANAGER TITLE
SELECT E.TITLEOFCOURTESY, (E.FIRSTNAME+' '+E.LASTNAME), E.TITLE, M.TITLEOFCOURTESY, (M.FIRSTNAME+' '+M.LASTNAME), M.TITLE
FROM EMPLOYEES E LEFT JOIN EMPLOYEES M ON E.REPORTSTO = M.EMPLOYEEID
